spring:
  datasource:
    username: root
    password: parola
    url: jdbc:mysql://localhost:3306/votingApp?useSSL=false&createDatabaseIfNotExist=true

  jpa:
    hibernate:
      ddl_auto: create-drop

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8081/realms/myrealm
          jwk-set-uri: http://localhost:8081/realms/myrealm/protocol/openid-connect/certs